services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: universal-homelab-mcp
    ports:
      - "3000:8000"
      - "3001:3001"
    environment:
      - DEBUG=true
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes:
      - ./inventory:/app/inventory
      - ./terraform:/app/terraform
      - ./.env:/app/.env:ro
      - ~/.ssh:/root/.ssh:ro  # For SSH key access (read-only)
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: mcp-web-client
    ports:
      - "5173:80"
    depends_on:
      - mcp-server
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Ollama service for local testing
  # Uncomment if you want to run Ollama in Docker
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama-local
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   networks:
  #     - mcp-network
  #   restart: unless-stopped

networks:
  mcp-network:
    driver: bridge

volumes:
  # Uncomment if using Ollama service
  # ollama_data:
  #   driver: local
  inventory_data:
    driver: local