name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_pattern:
        description: 'Test pattern to run (e.g., test_ssh or leave empty for all)'
        required: false
        default: ''
      python_version:
        description: 'Python version'
        required: false
        default: '3.12'
        type: choice
        options:
          - '3.10'
          - '3.11'
          - '3.12'
      run_integration:
        description: 'Run integration tests'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run specific tests
      if: inputs.test_pattern != ''
      run: |
        pytest -v -k "${{ inputs.test_pattern }}" --tb=short

    - name: Run all unit tests
      if: inputs.test_pattern == '' && !inputs.run_integration
      run: |
        pytest -v -m "not integration" --tb=short

    - name: Run all tests including integration
      if: inputs.test_pattern == '' && inputs.run_integration
      run: |
        pytest -v --tb=short